package practica3;

public enum TipoObstaculo {
    MURO_VERTICAL, MURO_HORIZONTAL,
    ESQUINA_ARRIBA_DERECHA, ESQUINA_ARRIBA_IZQUIERDA, ESQUINA_ABAJO_DERECHA, ESQUINA_ABAJO_IZQUIERDA,
    FIN_ARRIBA, FIN_ABAJO, FIN_IZQUIERDA, FIN_DERECHA,
}
